### ISSUE TITLE
Notice from passing variables by reference

### ISSUE THREAD

**Issue by ericnicolaas** [wp-pay-extensions/charitable#6]
This is happening both when returning from Mollie:

![screenshot 2017-11-23 16 49 00](https://user-images.githubusercontent.com/676582/33161947-576fd324-d06e-11e7-9a6e-bbe9dc6cbde0.png)

And when viewing the payment in the Pay dashboard:

![screenshot 2017-11-23 16 51 03](https://user-images.githubusercontent.com/676582/33161987-8fc324ec-d06e-11e7-834b-e7afae3011ab.png)

**Comment by rvdsteege** [comment]
Thanks, Eric. The issue has been resolved in https://github.com/wp-pay-extensions/charitable/commit/c7ae6dfab2e40d3db27b8766f2753c993560e6ea
