### ISSUE TITLE
Donation fails until payment gateway settings have been saved

### ISSUE THREAD

**Issue by ericnicolaas** [wp-pay-extensions/charitable#7]
We have had a couple customers reach out about a problem with the Pronamic iDEAL integration, and I eventually tracked down the issue. 

The symptom of this issue is that the donation form fails to submit, returning with a "Unable to process donation" error:

<img width="575" alt="screenshot 2017-12-09 10 53 16" src="https://user-images.githubusercontent.com/676582/33791144-3bd8f538-dccf-11e7-9db1-529b37057bc1.png">

"Unable to process donation" is a generic Charitable error we return when we know the donation failed, but we're not quite sure why (i.e. there may be a fatal error down the line) :)

I found that this issue went away after going to Charitable > Settings > Payment Gateways, clicking on the "Gateway Settings/Gateway-instellingen" button for the gateway they're using and then saving the settings without changing anything.

Based on that, I think that what is happening is that the Configuration/Configuratie setting is not correctly returning until the user has actually saved those settings. This is confusing/unexpected for users when there is only one configuration and it appears to be set automatically (i.e. if you activate one of the gateways, then go to the settings you'll see that configuration listed as the active configuration already). 

My suggestion would be that in cases where the configuration has not been saved, the default one is used (i.e. whatever is shown in the gateway settings should be used).

**Comment by rvdsteege** [comment]
Eric, thank you for reporting this issue. I've fixed this behaviour in https://github.com/wp-pay-extensions/charitable/commit/95b5ea49776b3caa8e5b5f59bddb7f740232c64c which will be included in the next plugin update.
